language: python
python:
  - "2.6"
  - "2.7"
sudo: true
install:
  - sudo add-apt-repository -y ppa:hrg/daily
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y pkg-config python-dev python-pip openrtm-aist-python python-omniorb omniidl-python omniorb-nameserver omniorb-idl omniidl
  - sudo pip install pyyaml rednose coverage coveralls
script: nosetests -v --rednose --with-doctest --with-coverage --cover-package=rtctree --cover-erase
after_success:
  coveralls
