language: cpp
sudo: true
install:
  - sudo add-apt-repository -y ppa:hrg/daily
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-pip python-dev openrtm-aist-python python-omniorb omniidl-python omniorb-nameserver omniorb-idl omniidl
  - sudo pip install pyyaml nose rednose coverage coveralls
script: nosetests -v --rednose --with-doctest --with-coverage --cover-package=rtctree --cover-erase
after_success:
  coveralls
